/*

    *** /etc/fstab ***

# HEADER: This file was autogenerated at Sun Jan 18 14:55:17 +0100 2009
# HEADER: by puppet.  While it can still be managed manually, it
# HEADER: is definitely not recommended.
# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc	/proc	proc	defaults	0	0
# /dev/sda1
UUID=c270dc80-0032-4a68-9efb-740e8230cf1e	/	ext3	relatime,errors=remount-ro	0	1
# /dev/sda5
UUID=a5a35e92-7f13-4e30-bac7-8bfa059f4a27	none	swap	sw	0	0
/dev/scd0	/media/cdrom0	udf,iso9660	user,noauto,exec,utf8	0	0
knuth:/home	/home	nfs	ro,intr,soft	0	0
knuth:/ping/knuth/home0	/ping/knuth/home0	nfs	rw,intr,hard,bg	0	0
knuth:/var/local/ping-config/ /var/local/ping-config/ nfs ro,intr,hard 0 0
*/


#ifndef LUAWEAPON_H
#define LUAWEAPON_H
#include "../lua.h"

// Fordi Raymond sier det.
void luaopen_weapon(lua_State *storL);

#endif

